# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 02:17
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('news_source', models.CharField(max_length=20, verbose_name='\u65b0\u95fb\u6765\u6e90')),
                ('news_pic', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='\u9644\u56fe')),
                ('news_content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6b63\u6587')),
                ('news_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Category', verbose_name='\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u5217\u8868',
                'verbose_name_plural': '\u65b0\u95fb\u5217\u8868',
            },
        ),
    ]
